# Generated by Django 3.0.8 on 2021-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('position', models.CharField(blank=True, max_length=400, null=True)),
                ('photo', models.FileField(upload_to='')),
                ('age', models.CharField(blank=True, max_length=400, null=True)),
                ('salary', models.CharField(blank=True, max_length=400, null=True)),
                ('office', models.CharField(max_length=250)),
            ],
        ),
    ]
